# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 14:16
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEvent',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
